---
# tasks file for hello-world
#- name: Debug Hello-world
#  debug:
#    msg: "Hello {{ hello_world_msg }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install template
  src: ../templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default.conf
