---
# tasks file for hello-world
#- name: Debug Hello-world
#  debug:
#    msg: "Hello {{ hello_world_msg }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default.conf
    owner: root
    group: root
    mode: 0644

- name: Creates directory
  file: 
    state: directory
    path: "{{ hello_world_route }}"
    owner: www-data
    group: www-data
    mode: 0755

- name: Deploy index.html from template
  template:
    src: index.html.j2
    path: "{{ hello_world_route }}"/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: Restart Nginx
  service: 
    state: restarted
    name: nginx 